#pragma once

template <class T>
class CProxy_ISRenderCollectionEvents : public IConnectionPointImpl<T, &__uuidof(_ISRenderCollectionEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
